marucha.settings:
  type: config_object
  label: 'Marucha settings'
  mapping:
      name:
        type: label
        label: 'Name'
        constraints:
          NotBlank:
            message: "入力してください！(スキーマファイル側で制御)"
